topolvm/pvc-autoresizer

docs/design.md
=> Design Docs

README.md, cmd/run.go, docs/design.md, runners/metrics_client.go, runners/pvc_autoresizer.go, runners/pvc_autoresizer_test.go, runners/suite_test.go
This PR includes a commit to fix the calculation of `increase` size of PVC because
the intention was to derive the `increase` size from `resources.requests.storage`,
not `resources.limits.storage`.
Also, it includes several commits to cleanup and enhance logs.
=> Fix increase size calculation

CHANGELOG.md, README.md, runners/constants.go, runners/pvc_autoresizer.go, runners/pvc_autoresizer_test.go
fixes https://github.com/topolvm/pvc-autoresizer/issues/31
Currently `.spec.resources.requests.storage` is the only mutable field on the PVC spec, so I am not sure if relying on `.spec.resources.limits.storage` is something you want to keep or not.
I am not a fun of having multiple ways of doing the same thing, so I think using an annotation exclusively for the PVC storage limit and dropping the usage of `.spec.resources.requests.storage` is a cleaner solution. This PR does **not** tackle this point. I just wanted to get your opinion on it and understand the reasoning behind it.
=> Provide PVC storage limit via annotations

runners/pvc_autoresizer.go
The controller shouldn't crash if a single PVC resize failure happens.
I run the controller with the flag `--no-annotation-check`, so it might be the case that someone sets the controller annotations on a PVC that is not resizable (StorageClass does not allow volume expansion). Right now this leads to stopping the processing for all PVCs.
I think it is safe to fail that single PVC and keep processing the others. Until we have metrics, relying on logged errors should be enough. WDYT ?
=> don't crash on a single PVC resizing failure

example/podpvc.yaml
Updates example to use preferred `storage_limit` annotation instead of `.spec.resources.limits.storage`
=> Update example to use preferred storage_limit annotation

metrics/resizer.go, metrics/resizer_test.go, runners/pvc_autoresizer.go
Adds PersistentVolumeClaim name to appropriate metrics. Before adding too many additional labels, wanted to get feedback on if this was an appropriate approach.
resolves #90
=> Extend metrics to include pvc name

e2e/Makefile
`make -C e2e clean` fails with the following error:
```
rm: cannot remove '/tmp/autoresizer/controller/pods': Permission denied
rm: cannot remove '/tmp/autoresizer/worker/pods': Permission denied
make: *** [Makefile:95: clean] Error 1
```
Even if executing with sudo, we get something like:
```
rm: cannot remove '/tmp/autoresizer/worker/pods/78b7ad42-aeb2-48b3-8c01-ef37cba63a00/volume-subpaths/web-config/prometheus/4': Device or resource busy
rm: cannot remove '/tmp/autoresizer/worker/pods/c4169fcb-6297-4053-9faa-9ae965962f3b/volume-subpaths/web-config/prometheus/4': Device or resource busy
make: *** [Makefile:95: clean] Error 1
```
These files are mount points. To teardown properly, unmount these before removing TMPDIR.
=> fix clean target of e2e/Makefile

runners/pvc_autoresizer.go, runners/pvc_autoresizer_test.go
#77
I modified to using a pvc capacity size to calculate the new storage request size.
This change requires pvc.status.capacity to be set, but for the major CSI drivers are set pvc.status.capacity to some value, so I don't think it's a problem.
- pvc.status.capacity is set the same value to linked pv.spec.capacity and the PVC is stored async: https://github.com/kubernetes/kubernetes/blob/v1.23.5/pkg/controller/volume/persistentvolume/pv_controller.go#L809
- pv.spec.capacity is set the CreateVolumeResponse.volume.capacity value if the pv was created by a CSI Driver: https://github.com/kubernetes-csi/external-provisioner/blob/v3.1.0/pkg/controller/controller.go#L744-L833
- above pv is saved by the sig-storage-lib-external-provisioner controller: …
=> Modify to using a pvc capacity for calculate new storage request

CODEOWNERS
Github assigns codeowers as reviewers to PR automatically and the assignment can not be changed.
To avoid that, use a team instead.
=> revise CODEOWNERS.

charts/pvc-autoresizer/README.md, charts/pvc-autoresizer/templates/controller/clusterrole.yaml, charts/pvc-autoresizer/templates/controller/clusterrolebinding.yaml, charts/pvc-autoresizer/templates/controller/deployment.yaml, charts/pvc-autoresizer/templates/controller/role.yaml, charts/pvc-autoresizer/templates/controller/rolebinding.yaml, charts/pvc-autoresizer/values.yaml, cmd/root.go, cmd/run.go
Hi, I am a fan on this project. I was hoping to contribute a change that would
add support for watching a small number of namespaces to better enable
deployment of this project in environments where broad permissions are heavily
scrutinized.
I didn't see much guidance with regards to contributions. Please let me know how
you feel about this type of change or any improvements I could make. The extent of
my testing was building this image and deploying it via the helm chart to a test kubernetes
cluster where it appears to behave as expected. I would appreciate any additional
testing guidance that could be provided.
* Adds support for namespace allow list. This is useful when running the
controller in clusters where cluster-scoped edit permissions are of
concern.
* Add controller argument …
=> Add support for namespace allow list

e2e/Makefile, runners/metrics_client.go, runners/pvc_autoresizer.go
The pvc-autoresizer decides whether each volume needs to be resized based on volume stats. This stats consists of available bytes, capacity, free inode count and all inode counts. The controller gets these values from prometheus metrics.
Without this patch, if metrics lack inodes counts for some target volumes, decision on resize necessity are done as if the lacking values are zero. This causes unnecessary resize for such volumes, and may continues to resize up to volume storage limit.
This patch changes reconciler to resize volume only if controller succeeded to get all four volume stats.
Fixes: #118 
---
Edit: I also updated TopoLVM version to reduce CI flakiness.
=> reconcile: do not resize volume if failed to get inode stats

e2e/Makefile
In the commit 35410dd47f78 ("e2e: bump TopoLVM version"), we bumped
TopoLVM version for e2e test to stabilize it, but there is still
flakiness [1]. This flakiness may be addressed in the commit
topolvm/topolvm@037a5b092d74 ("example: retry applying sample pods and
pvcs manifest"), so we bump TopoLVM version again.
[1] https://github.com/topolvm/pvc-autoresizer/runs/7036132661?check_suite_focus=true
=> e2e: bump TopoLVM version again

.github/workflows/project-bot.yaml
Due to the github change, worflows triggered by dependabot can not read
secrets. see
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
To fix this, we use pull_request_target instead.
=> Fix failing project-bot workflow triggered by dependabot.

.github/workflows/helm.yaml, .github/workflows/release.yaml
GitHub has announced that set-output and save-state will be discontinued.
We need to move to setting output parameters without these mechanisms.
Also, unnecessary steps have been removed.
=> github/workflows: Use output parameter instead of set-output command

e2e/testdata/pod-pvc-template.yaml, example/README.md, example/podpvc.yaml
also update a staled document.
Fix https://github.com/topolvm/pvc-autoresizer/issues/160
=> Replace quay.io/cybozu/ubuntu with official ubuntu

charts/pvc-autoresizer/README.md, charts/pvc-autoresizer/templates/controller/deployment.yaml, charts/pvc-autoresizer/values.yaml
Added the option to customize controller's podTemplate annotations using a new value `controller.podAnnotations`.
Rationale to introduce this change is being able to configure annotations for Prometheus Kubernetes service discovery, for cases when Prometheus Operator is not being used.
=> Helm chart | Added controller.podAnnotations to helm chart

Dockerfile, go.mod
By the error message below, go 1.19 looks to be required by some packages. And k8s 1.23, ~ 1.25 use go 1.19. So I try to update go 1.19.
https://github.com/topolvm/pvc-autoresizer/actions/runs/4081279918/jobs/7072721083
```
Error: ../../../go/pkg/mod/honnef.co/go/tools@v0.4.0/unused/unused.go:4[19](https://github.com/topolvm/pvc-autoresizer/actions/runs/4081279918/jobs/7072721083#step:7:20):14: obj.Origin undefined (type *types.Var has no field or method Origin)
Error: ../../../go/pkg/mod/honnef.co/go/tools@v0.4.0/unused/unused.go:4[21](https://github.com/topolvm/pvc-autoresizer/actions/runs/4081279918/jobs/7072721083#step:7:22):14: obj.Origin undefined (type *types.Func has no field or method Origin)
note: module requires Go 1.19
```
=> update go 1.19 to fix ci

docs/proposals/resize-when-creating-by-group.md
=> proposal: Expand the PVC's initial capacity based on the largest capacity in specified PVCs.

.github/workflows/helm-release.yaml
By adding cert-manager to dependency, we met the following error in chart release action.
```
Error: no repository definition for https://charts.jetstack.io/
```
We fixed it in the same way as TopoLVM.
https://github.com/topolvm/topolvm/blob/main/.github/workflows/helm-release.yaml#L26-L31
Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>
Co-authored-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
=> add cert-manager repo in the helm release action

.github/workflows/e2e.yaml
When only documents are updated, e2e test is not needed to be triggered.
In this PR, I prevent e2e test workflow from runnning when only documents are updated.
=> prevent e2e test workflow from running when only updating documents

README.md, docs/design.md, e2e/suite_test.go, e2e/testdata/pod-pvc-template.yaml, runners/pvc_autoresizer.go, runners/pvc_autoresizer_test.go
resolves: https://github.com/topolvm/pvc-autoresizer/issues/35
Also, I clarified the meaning of zero value for the storage limit annotation.
=> drop `resources.limits.storage` support

.github/workflows/stale.yaml
Issues labelled with update kubernetes would be marked as stale because dependent tools or libraries will not be released immediately.  To avoid this, add the label to exempt-issue-labels.
=> Refine exempt-issue-labels to ignore update kubernetes

.github/workflows/release.yaml, CHANGELOG.md, RELEASE.md, charts/pvc-autoresizer/CHANGELOG.md
Stop using the `CHANGELOG.md`,
and use release notes instead.
Similar PR for topolvm: https://github.com/topolvm/topolvm/pull/765
Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>
=> Stop using the CHANGELOG.md

README.md
It has been already deprecated long time ago, it is time to remove it.
=> Remove reference to quay.io repository

Makefile
Make commands stored in variables similar to e2e/Makfile.
=> make commands in values

Makefile, e2e/Makefile, versions.mk
Previously, versions were located at [1], but some were overlooked. This commit consolidates all versions into versions.mk.
[1]: https://github.com/topolvm/pvc-autoresizer/commit/ba88f0079b8a93272575c4a8ccdf08809f791dfd
=> Move tool versions into versions.mk

.github/workflows/e2e.yaml, charts/pvc-autoresizer/README.md, charts/pvc-autoresizer/templates/_helpers.tpl, charts/pvc-autoresizer/templates/controller/certificate.yaml, charts/pvc-autoresizer/templates/controller/deployment.yaml, charts/pvc-autoresizer/templates/controller/issuer.yaml, charts/pvc-autoresizer/templates/controller/mutatingwebhookconfiguration.yaml, charts/pvc-autoresizer/values.yaml, e2e/Makefile, e2e/manifests/values/values-without-cert-manager.yaml
What should the feature do:
Automatically create a certificate for a webhook in the absence of a cert-manager
What is use case behind this feature:
There is no need to install extra applications in the cluster and support them (cert-manager)
#223
=> Generating certificates without a cert-manager

Makefile, versions.mk
Currently, the CI is broken because the latest setup-envtest requires go 1.21 ([an example failed run](https://github.com/topolvm/pvc-autoresizer/actions/runs/8549418063/job/23424700661?pr=249)). This patch solves this problem by pinning setup-envtest to go 1.20.
See also:
- https://github.com/topolvm/topolvm/pull/865
- https://github.com/kubernetes-sigs/controller-runtime/issues/2744
- https://github.com/topolvm/pie/pull/115
=> pin setup-envtest to go 1.20

cmd/main.go, cmd/run.go
Fix #259 
This commit adds the following CLI options to tune logging:
- `-zap-devel`
- `-zap-encoder`
- `-zap-log-level`
- `-zap-stacktrace-level`
- `-zap-time-encoding`
See also: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/log/zap#Options.BindFlags
=> add CLI options for tuning logging

internal/runners/k8s_metrics_api_client.go
The Kubernetes API client runner currently does not increment the metric client failure metric if there is a failure.
This PR fixes this to match with the Prometheus client: https://github.com/topolvm/pvc-autoresizer/blob/fa8cd0ffca26f49a5a97619a8c5c03e28a1a6ebc/internal/runners/prometheus_client.go#L84
FYI I saw the [KubernetesClientFailTotal](https://github.com/topolvm/pvc-autoresizer/blob/fa8cd0ffca26f49a5a97619a8c5c03e28a1a6ebc/internal/metrics/kubernetes_client.go#L34-L36) metric, but I am assuming this should be reserved for listing PVCs etc. rather than for retrieving metrics
=> Increment failure metric for Kubernetes API client

charts/pvc-autoresizer/README.md, charts/pvc-autoresizer/templates/controller/deployment.yaml, charts/pvc-autoresizer/values.yaml
Fixes https://github.com/topolvm/pvc-autoresizer/issues/264
Adds two new helm values controller.securityContext, and controller.podSecurityContext - these correspond to Container level Security Context and Pod level Security Context respectively.
This may be leveraged to setup a security context complaint with pod security standards etc.
=> feat: support securityContext and podSecurityContext configuration

internal/runners/k8s_metrics_api_client.go
This PR fixes a bug reported in #266. Thanks @Mihirkumarsingh for reporting!
=> Fix concurrent map writes bug of K8s metrics API client

go.mod, internal/runners/k8s_metrics_api_client.go
The go module "github.com/pkg/errors" had been archived on 2021. In this commit we avoid using this module directly and use fmt.Errorf() from the standard library instead.
=> Avoid using github.com/pkg/errors directly

charts/pvc-autoresizer/templates/controller/certificate.yaml, charts/pvc-autoresizer/templates/controller/deployment.yaml, charts/pvc-autoresizer/templates/controller/issuer.yaml, cmd/main.go, cmd/run.go
Fixes https://github.com/topolvm/pvc-autoresizer/issues/271
When `.Values.webhook.pvcMutatingWebhook.enabled` is set false, ensure that any of the configuration related to the webhook server is not rendered. ie. cert manager certificate / issuer, deployment volume mount from secret etc.
This is supplemented with a new option `--webhook-enabled` - which by default is set true, to mirror existing behaviour. When it is explicitly set false, for example when `.Values.webhook.pvcMutatingWebhook.enabled` is set false the webhook server will not be configured.
ie.
```
helm install pvc-autoresizer ./charts/pvc-autoresizer --create-namespace --namespace=pvc-autoresizer --set "controller.args.prometheusURL=http://prom-kube-prometheus-stack-prometheus.default.svc:9090/" --set "image.tag=devel" --set …
```
=> fix: optionally disable the webhook server

charts/pvc-autoresizer/README.md, charts/pvc-autoresizer/templates/controller/deployment.yaml, charts/pvc-autoresizer/values.yaml
This will allow passing annotations at the deployment level. Allow supporting controllers which use the deployment annotations.
=> adding annotations to the deployment

charts/pvc-autoresizer/README.md, charts/pvc-autoresizer/templates/controller/deployment.yaml, charts/pvc-autoresizer/values.yaml
=> Add PriorityClassName and Affinity

charts/pvc-autoresizer/README.md, charts/pvc-autoresizer/templates/controller/serviceaccount.yaml, charts/pvc-autoresizer/values.yaml
Some users of the chart might need to adjust the `automountServiceAccountToken` value of the chart's ServiceAccount, or may want to supply their own ServiceAccount template instead. This change adds configuration options to allow these customizations.
=> Add additional configuration options for the chart ServiceAccount

charts/pvc-autoresizer/templates/controller/deployment.yaml, charts/pvc-autoresizer/templates/controller/podmonitor.yaml, charts/pvc-autoresizer/templates/controller/service.yaml
The current way the deployment labels are configured means the pods have only the `app.kubernetes.io/name` label by default. While users can add additional labels using the `controller.podLabels` value, generally it would be nice to provide the common labels (already generated in the tpl) on the pods by default.
Additionally, the current deployment `spec.selector.matchLabels` is hardcoded to a single static `app.kubernetes.io/name: pvc-autoresizer` label. This prevents users from running multiple deployments in the same cluster which can be useful in dev environments. A tpl function to generate the selector labels is already present so this change simply switches to using that.
This issue also applies to other resources like the PodMonitor and Service, so those have been updated to use …
=> Update the controller deployment labels to include more standard labels and use selector labels

.github/workflows/main.yaml, .github/workflows/release.yaml, Dockerfile, Makefile
This PR makes pvc-autoresizer container images available for linux/arm64 in addition to the current linux/amd64.
I updated the Dockerfile, Makefile, and GitHub Actions to use docker buildx and QEMU, just like the upstream topolvm project does. This keeps pvc-autoresizer build process consistent with the one from TopoLVM.
Resolves #267, resolves #299
=> Adds multi-platform support (and ARM64 compat)

docs/maintenance.md
We decided to update it alongside the Kubernetes update. The update policy is the same as TopoLVM for consistency.
=> Add a procedure to update Ubuntu

charts/pvc-autoresizer/templates/controller/mutatingwebhookconfiguration.yaml
On my cluster 1.33.4 it was not listening to all PVC (cf. https://github.com/topolvm/pvc-autoresizer/discussions/333).
=> Add namespace scope to the mutation webhook
