- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/issue.md
> add issue template for github

- .github/workflows/main.yaml
- .github/workflows/release.yaml
- Dockerfile
- RELEASE.md
- cmd/run.go
- config/rbac/leader_election_role.yaml
- go.mod
- runners/pvc_autoresizer.go
- runners/suite_test.go
> Update controller-runtime to v0.8.1

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
> add a template for feature request and a configure for question

- cmd/root.go
> Stop the display of usage when the program terminates with an error.

- runners/metrics_client.go
Hi, I deleted about used_bytes codes because this unused.
> Remove about used_bytes

- e2e/manifests/pvc-autoresizer/kustomization.yaml
> Fix e2e image

- RELEASE.md
> add a procedure to release Helm Chart

- metrics/resizer.go
- metrics/resizer_test.go
- runners/pvc_autoresizer.go
- runners/pvc_autoresizer_test.go
- runners/suite_test.go
The following implementation of #25 was missing, so I did it.
> Do not exit when some error occurs
> Don't exit if fail occurred

- README.md
Add prometheus metrics to README.md for #52.
> Add metrics description to README.md

- CHANGELOG.md
- config/default/kustomization.yaml
Update pvc-autoresizer version to 0.1.6
> Bump version to 0.1.6

- RELEASE.md
> improve changelog template

- charts/pvc-autoresizer/Chart.yaml
- charts/pvc-autoresizer/values.yaml
Update chart version to 0.2.0
Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>
> update chart version.

- docs/design.md
> update `Details` to match the latest implementation

- Makefile
- RELEASE.md
Added commands to RELEASE.md to update the version number.
It prevents the omission of updating the version number.
Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>
> Add commands to update the version number.

- CHANGELOG.md
- LICENSE
- Makefile
issue: topolvm/pvc-autoresizer#55
Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>
> Change license to Apache License Version 2.0.

- ct.yaml
We do not release the helm chart for each changes.
> Don't check version increment

- charts/pvc-autoresizer/Chart.yaml
Bump chart version to include nodeSelector and tolerations feature.
In some scenarios, PODs must be scheduled at specific nodes and evict other ones.
> Bump chart version to 0.3.1

- README.md
- docs/design.md
> inodes threshold doc

- .github/workflows/release.yaml
- Makefile
- README.md
- charts/pvc-autoresizer/README.md
- charts/pvc-autoresizer/values.yaml
- config/default/kustomization.yaml
- e2e/manifests/pvc-autoresizer/kustomization.yaml
- example/README.md
> Modified to use ghcr.io as a container registry

- e2e/Makefile
fixed:
- #101
ref:
- https://github.com/topolvm/topolvm/pull/457
- https://github.com/topolvm/topolvm/pull/469
> Update e2e topolvm version

- .github/workflows/project-bot.yaml
same as https://github.com/topolvm/topolvm/pull/504
> automate adding items to project

- charts/pvc-autoresizer/README.md
- charts/pvc-autoresizer/templates/controller/podmonitor.yaml
- charts/pvc-autoresizer/values.yaml
> add podMonitor

- docs/design.md
To ease to edit and delete dependency to external service.
> Use mermaid to draw diagram

- artifacthub-repo.yml
Signed-off-by: bells17 <bells171@gmail.com>
- https://github.com/topolvm/pvc-autoresizer/pull/169
- https://artifacthub.io/docs/topics/repositories/#verified-publisher
> Add artifacthub-repo.yml

- CHANGELOG.md
- config/default/kustomization.yaml
Signed-off-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
> Bump version to 0.6.1

- charts/pvc-autoresizer/CHANGELOG.md
- charts/pvc-autoresizer/Chart.yaml
- charts/pvc-autoresizer/values.yaml
Signed-off-by: ESASHIKA Kaoru <kaoru-esashika@cybozu.co.jp>
> Bump chart version to 0.7.0

- .gitignore
- Makefile
- RELEASE.md
- charts/pvc-autoresizer/Chart.yaml
- https://github.com/topolvm/topolvm/issues/368
- #169
> artifacthub

- .github/workflows/helm.yaml
- Dockerfile
- README.md
- charts/pvc-autoresizer/Chart.lock
- charts/pvc-autoresizer/Chart.yaml
- charts/pvc-autoresizer/README.md
- charts/pvc-autoresizer/templates/controller/certificate.yaml
- charts/pvc-autoresizer/templates/controller/deployment.yaml
- charts/pvc-autoresizer/templates/controller/issuer.yaml
- charts/pvc-autoresizer/templates/controller/mutatingwebhookconfiguration.yaml
- charts/pvc-autoresizer/templates/controller/service.yaml
- charts/pvc-autoresizer/values.yaml
- cmd/root.go
- cmd/run.go
- config/webhook/manifests.yaml
- ct.yaml
- e2e/Makefile
- e2e/suite_test.go
- e2e/testdata/pod-pvc-template.yaml
- hooks/persistentvolumeclaim.go
- runners/constants.go
- runners/pvc_autoresizer.go
- https://github.com/topolvm/pvc-autoresizer/pull/174
> Implement initial-resize-group-by feature

- .github/workflows/create-chart-update-pr.yaml
- RELEASE.md
Similar improvement with https://github.com/topolvm/topolvm/pull/768 .
Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>
> add a github workflow to create PRs for Helm Chart update

- README.md
> docs: remove "Project Status" from README.md

- test/e2e/suite_test.go
This attempts to fix the flakiness found on #279
> Fix flakines of mutating webhook
